//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string QuestionText { get; set; }
        public string CorrectAnswers { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Test Test { get; set; }
    }
}
